import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["strapi.movies.all"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data?.result && (
          <div>
            {data.result.map(({ attributes: { title } }) => (
              <h1 key={title}>{title}</h1>
            ))}
          </div>
        )}
      </div>
    </>
  );
};

export default Home;
