import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["strapi.movies.all"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data?.result && (
          <div>
            {data.result.map(({attributes: {title}}) => {
              console.log(title);

              return <h1 key={title}>{title}</h1>
            })}
          </div>
        )}

        {/* {data?.movies &&
          (data.movies.map((movie: any) => {
            {
              console.log(movie);
            }
            <h1>{movie.attributes.locale + ""}</h1>;
          }))} */}
      </div>
    </>
  );
};

export default Home;
